In [1]:
import numpy


In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
from numpy import*


In [ ]:
array([1,2,3])

In [4]:
array([1,2,3])

array([1, 2, 3])

In [5]:
import numpy as np


In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.__version__

'2.0.2'

In [8]:
array1=np.arange(100000)

In [9]:
array2=list(range(100000))

In [12]:
%time for i in range(10): my_array= array1= array1*2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 5 ms


In [13]:
help(np.sort)

Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None, *, stable=None)
    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and,
        in general, the actual implementation will vary with data type.
        The 'mergesort' option is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.

    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, sec

In [14]:
from numpy import doc

In [15]:
help(doc)

Help on package numpy.doc in numpy:

NAME
    numpy.doc

PACKAGE CONTENTS
    ufuncs

FILE
    (built-in)




In [17]:
help(np.doc.ufuncs)

<class 'AttributeError'>: module 'numpy.doc' has no attribute 'ufuncs'

In [ ]:
np.lookfor

In [18]:
np?

Type:        module
String form: <module 'numpy' from '/lib/python3.12/site-packages/numpy/__init__.py'>
File:        /lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``he

In [21]:
np.arange??

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [26]:
import numpy as np


In [27]:
my_list=list(range(10))
my_list_list

<class 'NameError'>: name 'my_list_list' is not defined